CREATE TABLE IF NOT EXISTS fines_app_constancias (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    establecimiento_id BIGINT UNSIGNED NULL,
    tipo VARCHAR(60) NOT NULL,
    titulo VARCHAR(190) NOT NULL,
    descripcion TEXT NOT NULL,
    clave VARCHAR(128) NOT NULL,
    nombres VARCHAR(120) NOT NULL,
    apellidos VARCHAR(120) NOT NULL,
    numero_documento VARCHAR(40) NOT NULL,
    datos_json JSON NULL,
    origen_sistema VARCHAR(80) NULL,
    origen_referencia VARCHAR(120) NULL,
    archivo_path VARCHAR(255) NULL,
    archivo_nombre VARCHAR(190) NULL,
    mime_type VARCHAR(120) NOT NULL DEFAULT 'application/pdf',
    creado_por INT UNSIGNED NULL,
    creado_en DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    anulado_en DATETIME NULL,
    UNIQUE KEY fines_app_constancias_clave_unique (clave),
    KEY fines_app_constancias_documento_index (numero_documento),
    KEY fines_app_constancias_origen_index (origen_sistema, origen_referencia),
    KEY fines_app_constancias_establecimiento_index (establecimiento_id),
    KEY fines_app_constancias_validacion_index (id, clave, anulado_en),
    KEY fines_app_constancias_creado_por_index (creado_por)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
