<?php

declare(strict_types=1);

use FinesApp\Controllers\AlumnoController;
use FinesApp\Controllers\AuthController;
use FinesApp\Controllers\CalendarioController;
use FinesApp\Controllers\ComisionController;
use FinesApp\Controllers\ComisionesPciController;
use FinesApp\Controllers\ComisionesPfController;
use FinesApp\Controllers\CursoController;
use FinesApp\Controllers\DashboardController;
use FinesApp\Controllers\DocenteController;
use FinesApp\Controllers\DocentesPfController;
use FinesApp\Controllers\HerramientasController;
use FinesApp\Controllers\InformeController;
use FinesApp\Controllers\PersonaController;
use FinesApp\Controllers\PlanillaDocenteController;
use FinesApp\Controllers\ProgramaFinesController;
use FinesApp\Controllers\SedeController;
use FinesApp\Controllers\TomaPosesionController;
use FinesApp\Core\App;
use FinesApp\Core\Request;

require dirname(__DIR__) . '/vendor/autoload.php';

$app = App::boot(dirname(__DIR__));
$request = Request::capture();
$app->get('/', [DashboardController::class, 'index']);
// Público (sin login)
$app->get('/toma-posesion', [TomaPosesionController::class, 'index']);
$app->get('/login', [AuthController::class, 'showLogin']);
$app->get('/login/google', [AuthController::class, 'redirectToGoogle']);
$app->get('/login/google/callback', [AuthController::class, 'handleGoogleCallback']);
$app->post('/logout', [AuthController::class, 'logout']);
$app->get('/programafines', [ProgramaFinesController::class, 'edit']);
$app->post('/programafines', [ProgramaFinesController::class, 'connect']);
$app->post('/programafines/desconectar', [ProgramaFinesController::class, 'disconnect']);
$app->get('/herramientas', [HerramientasController::class, 'index']);
$app->get('/informes', [InformeController::class, 'index']);
$app->get('/informes/egresados', [InformeController::class, 'egresados']);
$app->get('/informes/contralor', [InformeController::class, 'contralor']);
$app->post('/informes/contralor/asignar-planilla', [InformeController::class, 'asignarPlanillaContralor']);

$app->get('/personas', [PersonaController::class, 'index']);
$app->get('/personas/nueva', [PersonaController::class, 'createForm']);
$app->post('/personas', [PersonaController::class, 'create']);
$app->get('/personas/{id}/alumno', [AlumnoController::class, 'show']);
$app->get('/personas/{id}/docente', [DocenteController::class, 'show']);
$app->post('/personas/{id}', [AlumnoController::class, 'updatePersona']);
$app->post('/personas/{id}/docente', [DocenteController::class, 'updatePersona']);
$app->post('/personas/{id}/docente/tomas', [DocenteController::class, 'saveTomas']);
$app->post('/personas/{id}/alumno', [AlumnoController::class, 'saveAlumno']);
$app->post('/personas/{id}/alumno/calificaciones/sincronizar', [AlumnoController::class, 'sincronizarCalificaciones']);
$app->post('/personas/{id}/alumno/calificaciones', [AlumnoController::class, 'saveCalificaciones']);
$app->post('/personas/{id}/alumno/comisiones', [AlumnoController::class, 'saveComisiones']);
$app->post('/personas/{id}/alumno/comisiones/eliminar', [AlumnoController::class, 'deleteComision']);
$app->get('/comisiones/buscar', [AlumnoController::class, 'searchComisiones']);
$app->get('/cursos', [CursoController::class, 'index']);
$app->get('/cursos/{id}/planilla', [CursoController::class, 'planilla']);
$app->post('/cursos/{id}/planilla/consultar', [CursoController::class, 'planillaConsultar']);
$app->post('/cursos/{id}/planilla/guardar', [CursoController::class, 'planillaGuardar']);
$app->post('/cursos/{id}/planilla/entregada', [CursoController::class, 'marcarPlanillaEntregada']);
$app->get('/cursos/asociar', [AlumnoController::class, 'asociarCurso']);
$app->get('/docentes/procesar-pf', [DocentesPfController::class, 'form']);
$app->post('/docentes/procesar-pf', [DocentesPfController::class, 'process']);
$app->get('/comisiones', [ComisionController::class, 'index']);
$app->get('/comisiones/nueva', [ComisionController::class, 'createForm']);
$app->get('/comisiones/procesar-pf', [ComisionesPfController::class, 'form']);
$app->post('/comisiones/procesar-pf', [ComisionesPfController::class, 'process']);
$app->get('/comisiones/procesar-pci', [ComisionesPciController::class, 'form']);
$app->post('/comisiones/procesar-pci', [ComisionesPciController::class, 'process']);
$app->post('/comisiones', [ComisionController::class, 'create']);
$app->get('/comisiones/{id}', [ComisionController::class, 'admin']);
$app->post('/comisiones/{id}', [ComisionController::class, 'saveComision']);
$app->post('/comisiones/{id}/eliminar', [ComisionController::class, 'deleteComision']);
$app->post('/comisiones/{id}/generar-siguiente', [ComisionController::class, 'generarSiguiente']);
$app->post('/comisiones/{id}/transferir-alumnos-activos', [ComisionController::class, 'transferirAlumnosActivos']);
$app->post('/comisiones/{id}/reactivar-alumnos', [ComisionController::class, 'reactivarAlumnos']);
$app->post('/comisiones/{id}/cursos', [ComisionController::class, 'saveCursos']);
$app->post('/comisiones/{id}/cursos/agregar', [ComisionController::class, 'addCurso']);
$app->post('/comisiones/{id}/tomas', [ComisionController::class, 'saveTomas']);
$app->post('/comisiones/{id}/tomas/agregar', [ComisionController::class, 'addToma']);
$app->get('/comisiones/{id}/alumnos', [ComisionController::class, 'alumnos']);
$app->get('/comisiones/{id}/rindex', [ComisionController::class, 'rindex']);
$app->get('/sedes', [SedeController::class, 'index']);
$app->get('/sedes/nueva', [SedeController::class, 'createForm']);
$app->post('/sedes', [SedeController::class, 'create']);
$app->get('/sedes/{id}', [SedeController::class, 'edit']);
$app->post('/sedes/{id}', [SedeController::class, 'update']);
$app->post('/sedes/{id}/designaciones', [SedeController::class, 'saveDesignaciones']);
$app->post('/sedes/{id}/designaciones/agregar', [SedeController::class, 'addDesignacion']);
$app->get('/calendarios', [CalendarioController::class, 'index']);
$app->get('/calendarios/nuevo', [CalendarioController::class, 'createForm']);
$app->post('/calendarios', [CalendarioController::class, 'create']);
$app->get('/calendarios/{id}', [CalendarioController::class, 'edit']);
$app->post('/calendarios/{id}', [CalendarioController::class, 'update']);
$app->get('/planillas-docente', [PlanillaDocenteController::class, 'index']);
$app->get('/planillas-docente/nueva', [PlanillaDocenteController::class, 'createForm']);
$app->post('/planillas-docente', [PlanillaDocenteController::class, 'create']);
$app->get('/planillas-docente/{id}', [PlanillaDocenteController::class, 'edit']);
$app->post('/planillas-docente/{id}', [PlanillaDocenteController::class, 'update']);
$app->post('/comisiones/{id}/programafines/enviar', [ComisionController::class, 'enviarAlumnoProgramaFines']);
$app->post('/comisiones/{id}/programafines/sincronizar', [ComisionController::class, 'sincronizarProgramaFines']);
$app->post('/comisiones/{id}/programafines/importar', [ComisionController::class, 'importarAlumnoProgramaFines']);
$app->post('/comisiones/{id}/programafines/quitar', [ComisionController::class, 'quitarAlumnoProgramaFines']);
$app->post('/personas/{id}/programafines/actualizar', [AlumnoController::class, 'actualizarProgramaFines']);

$app->dispatch($request);
