//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinesApp.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FinesApp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FinesApp.
        /// </summary>
        public static string AppDisplayName {
            get {
                return ResourceManager.GetString("AppDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Informe Comision.
        /// </summary>
        public static string InformeComisionPageTitle {
            get {
                return ResourceManager.GetString("InformeComisionPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bienvenidos!.
        /// </summary>
        public static string MainPageTitle {
            get {
                return ResourceManager.GetString("MainPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Procesar Planilla Calificaciones.
        /// </summary>
        public static string ProcesarPlanillaCalificacionesPageTitle {
            get {
                return ResourceManager.GetString("ProcesarPlanillaCalificacionesPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ProcesarRegistroAlumnos.
        /// </summary>
        public static string ProcesarRegistroAlumnosPageTitle {
            get {
                return ResourceManager.GetString("ProcesarRegistroAlumnosPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Volver.
        /// </summary>
        public static string ShellGoBackButton {
            get {
                return ResourceManager.GetString("ShellGoBackButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a _Archivo.
        /// </summary>
        public static string ShellMenuFileHeader {
            get {
                return ResourceManager.GetString("ShellMenuFileHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a _Salir.
        /// </summary>
        public static string ShellMenuItemFileExitHeader {
            get {
                return ResourceManager.GetString("ShellMenuItemFileExitHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Informe Comision.
        /// </summary>
        public static string ShellMenuItemViewsInformeComisionPageHeader {
            get {
                return ResourceManager.GetString("ShellMenuItemViewsInformeComisionPageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inicio.
        /// </summary>
        public static string ShellMenuItemViewsMainPageHeader {
            get {
                return ResourceManager.GetString("ShellMenuItemViewsMainPageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Procesar Planilla Calificaciones.
        /// </summary>
        public static string ShellMenuItemViewsProcesarPlanillaCalificacionesPageHeader {
            get {
                return ResourceManager.GetString("ShellMenuItemViewsProcesarPlanillaCalificacionesPageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Procesar Registro Alumnos.
        /// </summary>
        public static string ShellMenuItemViewsProcesarRegistroAlumnosPageHeader {
            get {
                return ResourceManager.GetString("ShellMenuItemViewsProcesarRegistroAlumnosPageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Transferir Alumno.
        /// </summary>
        public static string ShellMenuItemViewsTransferirAlumnoPageHeader {
            get {
                return ResourceManager.GetString("ShellMenuItemViewsTransferirAlumnoPageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a _Administración.
        /// </summary>
        public static string ShellMenuViewsHeader {
            get {
                return ResourceManager.GetString("ShellMenuViewsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Transferir Alumno.
        /// </summary>
        public static string TransferirAlumnoPageTitle {
            get {
                return ResourceManager.GetString("TransferirAlumnoPageTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to TomasSemestre.
        /// </summary>
        public static string TomasSemestrePageTitle
        {
            get
            {
                return ResourceManager.GetString("TomasSemestrePageTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to MenuItemViewsTomasSemestrePageHeader.
        /// </summary>
        public static string ShellMenuItemViewsTomasSemestrePageHeader
        {
            get
            {
                return ResourceManager.GetString("ShellMenuItemViewsTomasSemestrePageHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ComisionesSemestre.
        /// </summary>
        public static string ComisionesSemestrePageTitle
        {
            get
            {
                return ResourceManager.GetString("ComisionesSemestrePageTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to MenuItemViewsComisionesSemestrePageHeader.
        /// </summary>
        public static string ShellMenuItemViewsComisionesSemestrePageHeader
        {
            get
            {
                return ResourceManager.GetString("ShellMenuItemViewsComisionesSemestrePageHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to CursosSemestre.
        /// </summary>
        public static string CursosSemestrePageTitle
        {
            get
            {
                return ResourceManager.GetString("CursosSemestrePageTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to MenuItemViewsCursosSemestrePageHeader.
        /// </summary>
        public static string ShellMenuItemViewsCursosSemestrePageHeader
        {
            get
            {
                return ResourceManager.GetString("ShellMenuItemViewsCursosSemestrePageHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to SedesSemestre.
        /// </summary>
        public static string SedesSemestrePageTitle
        {
            get
            {
                return ResourceManager.GetString("SedesSemestrePageTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to MenuItemViewsSedesSemestrePageHeader.
        /// </summary>
        public static string ShellMenuItemViewsSedesSemestrePageHeader
        {
            get
            {
                return ResourceManager.GetString("ShellMenuItemViewsSedesSemestrePageHeader", resourceCulture);
            }
        }
    }
}
